import {
  LayoutDashboard,
  CalendarDays,
  Megaphone,
  ListChecks,
  Building2,
  GitBranch,
  CalendarRange,
  GraduationCap,
  LayoutPanelTop,
  BookType,
  Users,
  Presentation,
  UserCheck,
  ClipboardCheck,
  Table2,
  Armchair,
  BookOpenCheck,
  PenLine,
  FileSpreadsheet,
  CalendarClock,
  Ticket,
  PenSquare,
  ScrollText,
  IdCard,
  Coins,
  Tags,
  Award,
  Receipt,
  Wallet,
  ChartColumnDecreasing,
  Bus,
  UserCog,
  Route,
  MapPin,
  LocateFixed,
  Cpu,
  BookOpen,
  BookMarked,
  BookUp,
  BookDown,
  CircleDollarSign,
  Building,
  DoorOpen,
  DoorClosed,
  Bed,
  Bell,
  MessageSquare,
  Mail,
  Send,
  MessageCircle,
  BarChart3,
  ChartArea,
  ChartNoAxesColumn,
  ChartPie,
  ChartLine,
  FileCog,
  Shield,
  UserPlus,
  KeyRound,
  Scroll,
  Activity,
  Plug,
  AtSign,
  CreditCard,
  Map,
  HardDrive,
  BrainCircuit,
  Wrench,
  Palette,
  DatabaseBackup,
  ShieldAlert,
  BookOpenText,
  Headphones,
  MessageSquareHeart,
  Info,
  UserCircle,
  SlidersHorizontal,
  Lock,
  LogOut,
} from 'lucide-react';
import type { NavGroup } from '@/types/navigation';

export const sidebarNav: NavGroup[] = [
  {
    title: 'Overview',
    items: [
      { title: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
      { title: 'Calendar', href: '/calendar', icon: CalendarDays },
      { title: 'Announcements', href: '/announcements', icon: Megaphone, badge: 3 },
      { title: 'Tasks', href: '/tasks', icon: ListChecks },
    ],
  },
  {
    title: 'School Management',
    items: [
      { title: 'Schools', href: '/schools', icon: Building2, badge: 'SA' },
      { title: 'Branches', href: '/branches', icon: GitBranch },
      { title: 'Academic Years', href: '/academic-years', icon: CalendarRange },
      { title: 'Classes', href: '/classes', icon: GraduationCap },
      { title: 'Sections', href: '/sections', icon: LayoutPanelTop },
      { title: 'Subjects', href: '/subjects', icon: BookType },
    ],
  },
  {
    title: 'Academics',
    items: [
      { title: 'Students', href: '/students', icon: Users },
      { title: 'Teachers', href: '/teachers', icon: Presentation },
      { title: 'Parents', href: '/parents', icon: UserCheck },
      { title: 'Attendance', href: '/attendance', icon: ClipboardCheck },
      { title: 'Timetable', href: '/timetable', icon: Table2 },
      { title: 'Seating', href: '/seating', icon: Armchair },
      { title: 'Homework', href: '/homework', icon: BookOpenCheck },
      { title: 'Assignments', href: '/assignments', icon: PenLine },
    ],
  },
  {
    title: 'Examinations',
    items: [
      {
        title: 'Exams',
        href: '/examinations',
        icon: FileSpreadsheet,
        subItems: [
          { title: 'Exam Schedule', href: '/examinations/schedule', icon: CalendarClock },
          { title: 'Hall Tickets', href: '/examinations/hall-tickets', icon: Ticket },
          { title: 'Marks Entry', href: '/examinations/marks', icon: PenSquare },
          { title: 'Results', href: '/examinations/results', icon: ScrollText },
          { title: 'Report Cards', href: '/examinations/report-cards', icon: IdCard },
        ],
      },
    ],
  },
  {
    title: 'Finance',
    items: [
      {
        title: 'Fee Collection',
        href: '/fees',
        icon: Coins,
        subItems: [
          { title: 'Fee Categories', href: '/fees/categories', icon: Tags },
          { title: 'Scholarships', href: '/fees/scholarships', icon: Award },
          { title: 'Expenses', href: '/fees/expenses', icon: Receipt },
          { title: 'Payroll', href: '/fees/payroll', icon: Wallet, disabled: true },
          { title: 'Financial Reports', href: '/fees/reports', icon: ChartColumnDecreasing },
        ],
      },
    ],
  },
  {
    title: 'Transport',
    items: [
      {
        title: 'Transport',
        href: '/transport',
        icon: Bus,
        subItems: [
          { title: 'Bus Fleet', href: '/transport/fleet', icon: Bus },
          { title: 'Drivers', href: '/transport/drivers', icon: UserCog },
          { title: 'Routes', href: '/transport/routes', icon: Route },
          { title: 'Stops', href: '/transport/stops', icon: MapPin },
          { title: 'Live Tracking', href: '/transport/tracking', icon: LocateFixed },
          { title: 'GPS Devices', href: '/transport/devices', icon: Cpu },
        ],
      },
    ],
  },
  {
    title: 'Library',
    items: [
      {
        title: 'Library',
        href: '/library',
        icon: BookOpen,
        subItems: [
          { title: 'Books', href: '/library/books', icon: BookMarked },
          { title: 'Categories', href: '/library/categories', icon: BookType },
          { title: 'Book Issue', href: '/library/issue', icon: BookUp },
          { title: 'Book Return', href: '/library/return', icon: BookDown },
          { title: 'Fine Management', href: '/library/fines', icon: CircleDollarSign },
        ],
      },
    ],
  },
  {
    title: 'Hostel',
    items: [
      { title: 'Hostels', href: '/hostel', icon: Building },
      { title: 'Rooms', href: '/hostel/rooms', icon: DoorOpen },
      { title: 'Room Allocation', href: '/hostel/allocation', icon: DoorClosed },
      { title: 'Hostel Attendance', href: '/hostel/attendance', icon: Bed },
    ],
  },
  {
    title: 'Communication',
    items: [
      { title: 'Notifications', href: '/notifications', icon: Bell },
      { title: 'SMS', href: '/sms', icon: MessageSquare },
      { title: 'Email', href: '/email', icon: Mail },
      { title: 'Circulars', href: '/circulars', icon: Send },
      { title: 'Parent Messages', href: '/parent-messages', icon: MessageCircle },
    ],
  },
  {
    title: 'Reports & Analytics',
    items: [
      { title: 'Dashboard Reports', href: '/reports', icon: BarChart3 },
      { title: 'Attendance Reports', href: '/reports/attendance', icon: ChartArea },
      { title: 'Academic Reports', href: '/reports/academic', icon: ChartNoAxesColumn },
      { title: 'Financial Reports', href: '/reports/financial', icon: ChartPie },
      { title: 'Transport Reports', href: '/reports/transport', icon: ChartLine },
      { title: 'Custom Reports', href: '/reports/custom', icon: FileCog },
    ],
  },
  {
    title: 'Administration',
    items: [
      { title: 'Users', href: '/admin/users', icon: UserPlus },
      { title: 'Roles', href: '/admin/roles', icon: Shield },
      { title: 'Permissions', href: '/admin/permissions', icon: KeyRound },
      { title: 'Audit Logs', href: '/admin/audit-logs', icon: Scroll },
      { title: 'Activity Logs', href: '/admin/activity-logs', icon: Activity },
    ],
  },
  {
    title: 'Integrations',
    items: [
      { title: 'Email', href: '/integrations/email', icon: AtSign },
      { title: 'SMS Gateway', href: '/integrations/sms', icon: MessageSquare },
      { title: 'Payment Gateway', href: '/integrations/payments', icon: CreditCard },
      { title: 'Maps', href: '/integrations/maps', icon: Map },
      { title: 'Storage', href: '/integrations/storage', icon: HardDrive },
      { title: 'AI Services', href: '/integrations/ai', icon: BrainCircuit },
    ],
  },
  {
    title: 'Platform',
    items: [
      { title: 'Settings', href: '/settings', icon: Wrench },
      { title: 'Branding', href: '/settings/branding', icon: Palette },
      { title: 'Themes', href: '/settings/themes', icon: Palette },
      { title: 'Backup & Restore', href: '/settings/backup', icon: DatabaseBackup },
      { title: 'Maintenance Mode', href: '/settings/maintenance', icon: ShieldAlert },
    ],
  },
  {
    title: 'Help',
    items: [
      { title: 'Documentation', href: '/docs', icon: BookOpenText },
      { title: 'Support', href: '/support', icon: Headphones, badge: 2 },
      { title: 'Feedback', href: '/feedback', icon: MessageSquareHeart },
      { title: 'About', href: '/about', icon: Info },
    ],
  },
  {
    title: 'Account',
    items: [
      { title: 'Profile', href: '/profile', icon: UserCircle },
      { title: 'Preferences', href: '/preferences', icon: SlidersHorizontal },
      { title: 'Security', href: '/security', icon: Lock },
      { title: 'Logout', href: '/logout', icon: LogOut },
    ],
  },
];
