import type { RouteConfig } from '@/types/navigation';

function bc(...crumbs: { label: string; href?: string }[]): RouteConfig['breadcrumbs'] {
  return crumbs;
}

export const routeConfig: Record<string, RouteConfig> = {
  '/dashboard': { title: 'Dashboard', description: 'Overview of your school', breadcrumbs: bc({ label: 'Dashboard' }) },
  '/calendar': { title: 'Calendar', description: 'School calendar and events', breadcrumbs: bc({ label: 'Overview' }, { label: 'Calendar' }) },
  '/announcements': { title: 'Announcements', description: 'School announcements', breadcrumbs: bc({ label: 'Overview' }, { label: 'Announcements' }) },
  '/tasks': { title: 'Tasks', description: 'Manage your tasks', breadcrumbs: bc({ label: 'Overview' }, { label: 'Tasks' }) },
  '/schools': { title: 'Schools', description: 'Manage registered schools', breadcrumbs: bc({ label: 'School Management' }, { label: 'Schools' }) },
  '/branches': { title: 'Branches', description: 'Manage school branches', breadcrumbs: bc({ label: 'School Management' }, { label: 'Branches' }) },
  '/academic-years': { title: 'Academic Years', description: 'Manage academic years', breadcrumbs: bc({ label: 'School Management' }, { label: 'Academic Years' }) },
  '/classes': { title: 'Classes', description: 'Manage classes', breadcrumbs: bc({ label: 'School Management' }, { label: 'Classes' }) },
  '/sections': { title: 'Sections', description: 'Manage class sections', breadcrumbs: bc({ label: 'School Management' }, { label: 'Sections' }) },
  '/subjects': { title: 'Subjects', description: 'Manage subjects', breadcrumbs: bc({ label: 'School Management' }, { label: 'Subjects' }) },
  '/students': { title: 'Students', description: 'Manage student records', breadcrumbs: bc({ label: 'Academics' }, { label: 'Students' }) },
  '/teachers': { title: 'Teachers', description: 'Manage teacher records', breadcrumbs: bc({ label: 'Academics' }, { label: 'Teachers' }) },
  '/parents': { title: 'Parents', description: 'Manage parent and guardian records', breadcrumbs: bc({ label: 'Academics' }, { label: 'Parents' }) },
  '/attendance': { title: 'Attendance', description: 'Track student attendance', breadcrumbs: bc({ label: 'Academics' }, { label: 'Attendance' }) },
  '/timetable': { title: 'Timetable', description: 'Manage class timetables', breadcrumbs: bc({ label: 'Academics' }, { label: 'Timetable' }) },
  '/seating': { title: 'Seating', description: 'Classroom seating arrangement', breadcrumbs: bc({ label: 'Academics' }, { label: 'Seating' }) },
  '/homework': { title: 'Homework', description: 'Manage homework assignments', breadcrumbs: bc({ label: 'Academics' }, { label: 'Homework' }) },
  '/assignments': { title: 'Assignments', description: 'Manage assignments', breadcrumbs: bc({ label: 'Academics' }, { label: 'Assignments' }) },
  '/examinations': { title: 'Examinations', description: 'Manage exams', breadcrumbs: bc({ label: 'Examinations' }, { label: 'Exams' }) },
  '/examinations/schedule': { title: 'Exam Schedule', description: 'View exam schedule', breadcrumbs: bc({ label: 'Examinations' }, { label: 'Schedule' }) },
  '/examinations/hall-tickets': { title: 'Hall Tickets', description: 'Generate hall tickets', breadcrumbs: bc({ label: 'Examinations' }, { label: 'Hall Tickets' }) },
  '/examinations/marks': { title: 'Marks Entry', description: 'Enter exam marks', breadcrumbs: bc({ label: 'Examinations' }, { label: 'Marks Entry' }) },
  '/examinations/results': { title: 'Results', description: 'View exam results', breadcrumbs: bc({ label: 'Examinations' }, { label: 'Results' }) },
  '/examinations/report-cards': { title: 'Report Cards', description: 'Generate report cards', breadcrumbs: bc({ label: 'Examinations' }, { label: 'Report Cards' }) },
  '/fees': { title: 'Fee Collection', description: 'Manage fee collection', breadcrumbs: bc({ label: 'Finance' }, { label: 'Fee Collection' }) },
  '/fees/categories': { title: 'Fee Categories', description: 'Manage fee categories', breadcrumbs: bc({ label: 'Finance' }, { label: 'Fee Categories' }) },
  '/fees/scholarships': { title: 'Scholarships', description: 'Manage scholarships', breadcrumbs: bc({ label: 'Finance' }, { label: 'Scholarships' }) },
  '/fees/expenses': { title: 'Expenses', description: 'Track expenses', breadcrumbs: bc({ label: 'Finance' }, { label: 'Expenses' }) },
  '/fees/payroll': { title: 'Payroll', description: 'Manage payroll (Coming Soon)', breadcrumbs: bc({ label: 'Finance' }, { label: 'Payroll' }) },
  '/fees/reports': { title: 'Financial Reports', description: 'View financial reports', breadcrumbs: bc({ label: 'Finance' }, { label: 'Financial Reports' }) },
  '/transport': { title: 'Transport', description: 'Manage transportation', breadcrumbs: bc({ label: 'Transport' }, { label: 'Overview' }) },
  '/transport/fleet': { title: 'Bus Fleet', description: 'Manage bus fleet', breadcrumbs: bc({ label: 'Transport' }, { label: 'Bus Fleet' }) },
  '/transport/drivers': { title: 'Drivers', description: 'Manage drivers', breadcrumbs: bc({ label: 'Transport' }, { label: 'Drivers' }) },
  '/transport/routes': { title: 'Routes', description: 'Manage transport routes', breadcrumbs: bc({ label: 'Transport' }, { label: 'Routes' }) },
  '/transport/stops': { title: 'Stops', description: 'Manage bus stops', breadcrumbs: bc({ label: 'Transport' }, { label: 'Stops' }) },
  '/transport/tracking': { title: 'Live Tracking', description: 'Track buses in real-time', breadcrumbs: bc({ label: 'Transport' }, { label: 'Live Tracking' }) },
  '/transport/devices': { title: 'GPS Devices', description: 'Manage GPS devices', breadcrumbs: bc({ label: 'Transport' }, { label: 'GPS Devices' }) },
  '/library': { title: 'Library', description: 'Manage library', breadcrumbs: bc({ label: 'Library' }, { label: 'Overview' }) },
  '/library/books': { title: 'Books', description: 'Manage library books', breadcrumbs: bc({ label: 'Library' }, { label: 'Books' }) },
  '/library/categories': { title: 'Categories', description: 'Book categories', breadcrumbs: bc({ label: 'Library' }, { label: 'Categories' }) },
  '/library/issue': { title: 'Book Issue', description: 'Issue books to students', breadcrumbs: bc({ label: 'Library' }, { label: 'Issue' }) },
  '/library/return': { title: 'Book Return', description: 'Return borrowed books', breadcrumbs: bc({ label: 'Library' }, { label: 'Return' }) },
  '/library/fines': { title: 'Fine Management', description: 'Manage library fines', breadcrumbs: bc({ label: 'Library' }, { label: 'Fines' }) },
  '/hostel': { title: 'Hostels', description: 'Manage hostels', breadcrumbs: bc({ label: 'Hostel' }, { label: 'Hostels' }) },
  '/hostel/rooms': { title: 'Rooms', description: 'Manage hostel rooms', breadcrumbs: bc({ label: 'Hostel' }, { label: 'Rooms' }) },
  '/hostel/allocation': { title: 'Room Allocation', description: 'Allocate rooms to students', breadcrumbs: bc({ label: 'Hostel' }, { label: 'Allocation' }) },
  '/hostel/attendance': { title: 'Hostel Attendance', description: 'Track hostel attendance', breadcrumbs: bc({ label: 'Hostel' }, { label: 'Attendance' }) },
  '/notifications': { title: 'Notifications', description: 'Manage notifications', breadcrumbs: bc({ label: 'Communication' }, { label: 'Notifications' }) },
  '/sms': { title: 'SMS', description: 'Send SMS messages', breadcrumbs: bc({ label: 'Communication' }, { label: 'SMS' }) },
  '/email': { title: 'Email', description: 'Send emails', breadcrumbs: bc({ label: 'Communication' }, { label: 'Email' }) },
  '/circulars': { title: 'Circulars', description: 'Manage circulars', breadcrumbs: bc({ label: 'Communication' }, { label: 'Circulars' }) },
  '/parent-messages': { title: 'Parent Messages', description: 'Send parent messages', breadcrumbs: bc({ label: 'Communication' }, { label: 'Parent Messages' }) },
  '/reports': { title: 'Dashboard Reports', description: 'View dashboard reports', breadcrumbs: bc({ label: 'Reports & Analytics' }, { label: 'Dashboard Reports' }) },
  '/reports/attendance': { title: 'Attendance Reports', description: 'View attendance reports', breadcrumbs: bc({ label: 'Reports & Analytics' }, { label: 'Attendance' }) },
  '/reports/academic': { title: 'Academic Reports', description: 'View academic reports', breadcrumbs: bc({ label: 'Reports & Analytics' }, { label: 'Academic' }) },
  '/reports/financial': { title: 'Financial Reports', description: 'View financial reports', breadcrumbs: bc({ label: 'Reports & Analytics' }, { label: 'Financial' }) },
  '/reports/transport': { title: 'Transport Reports', description: 'View transport reports', breadcrumbs: bc({ label: 'Reports & Analytics' }, { label: 'Transport' }) },
  '/reports/custom': { title: 'Custom Reports', description: 'Create custom reports', breadcrumbs: bc({ label: 'Reports & Analytics' }, { label: 'Custom Reports' }) },
  '/admin/users': { title: 'Users', description: 'Manage system users', breadcrumbs: bc({ label: 'Administration' }, { label: 'Users' }) },
  '/admin/roles': { title: 'Roles', description: 'Manage user roles', breadcrumbs: bc({ label: 'Administration' }, { label: 'Roles' }) },
  '/admin/permissions': { title: 'Permissions', description: 'Manage permissions', breadcrumbs: bc({ label: 'Administration' }, { label: 'Permissions' }) },
  '/admin/audit-logs': { title: 'Audit Logs', description: 'View audit logs', breadcrumbs: bc({ label: 'Administration' }, { label: 'Audit Logs' }) },
  '/admin/activity-logs': { title: 'Activity Logs', description: 'View activity logs', breadcrumbs: bc({ label: 'Administration' }, { label: 'Activity Logs' }) },
  '/integrations/email': { title: 'Email', description: 'Configure email integration', breadcrumbs: bc({ label: 'Integrations' }, { label: 'Email' }) },
  '/integrations/sms': { title: 'SMS Gateway', description: 'Configure SMS gateway', breadcrumbs: bc({ label: 'Integrations' }, { label: 'SMS' }) },
  '/integrations/payments': { title: 'Payment Gateway', description: 'Configure payment gateway', breadcrumbs: bc({ label: 'Integrations' }, { label: 'Payments' }) },
  '/integrations/maps': { title: 'Maps', description: 'Configure map services', breadcrumbs: bc({ label: 'Integrations' }, { label: 'Maps' }) },
  '/integrations/storage': { title: 'Storage', description: 'Configure storage', breadcrumbs: bc({ label: 'Integrations' }, { label: 'Storage' }) },
  '/integrations/ai': { title: 'AI Services', description: 'Configure AI services', breadcrumbs: bc({ label: 'Integrations' }, { label: 'AI' }) },
  '/settings': { title: 'Settings', description: 'Manage system settings', breadcrumbs: bc({ label: 'Platform' }, { label: 'Settings' }) },
  '/settings/branding': { title: 'Branding', description: 'Customize branding', breadcrumbs: bc({ label: 'Platform' }, { label: 'Branding' }) },
  '/settings/themes': { title: 'Themes', description: 'Manage themes', breadcrumbs: bc({ label: 'Platform' }, { label: 'Themes' }) },
  '/settings/backup': { title: 'Backup & Restore', description: 'Backup and restore data', breadcrumbs: bc({ label: 'Platform' }, { label: 'Backup & Restore' }) },
  '/settings/maintenance': { title: 'Maintenance Mode', description: 'Manage maintenance mode', breadcrumbs: bc({ label: 'Platform' }, { label: 'Maintenance' }) },
  '/docs': { title: 'Documentation', description: 'View documentation', breadcrumbs: bc({ label: 'Help' }, { label: 'Documentation' }) },
  '/support': { title: 'Support', description: 'Get support', breadcrumbs: bc({ label: 'Help' }, { label: 'Support' }) },
  '/feedback': { title: 'Feedback', description: 'Send feedback', breadcrumbs: bc({ label: 'Help' }, { label: 'Feedback' }) },
  '/about': { title: 'About', description: 'About SchoolOS', breadcrumbs: bc({ label: 'Help' }, { label: 'About' }) },
  '/profile': { title: 'Profile', description: 'Manage your profile', breadcrumbs: bc({ label: 'Account' }, { label: 'Profile' }) },
  '/preferences': { title: 'Preferences', description: 'Manage preferences', breadcrumbs: bc({ label: 'Account' }, { label: 'Preferences' }) },
  '/security': { title: 'Security', description: 'Security settings', breadcrumbs: bc({ label: 'Account' }, { label: 'Security' }) },
};

export function getRouteConfig(pathname: string): RouteConfig | undefined {
  return routeConfig[pathname];
}
