export const WIDGET_PERMISSIONS: Record<string, string | undefined> = {
  studentCount: 'students:read',
  teacherCount: 'users:read',
  parentCount: 'parents:read',
  staffCount: 'users:read',
  admissionsToday: 'students:read',
  attendanceSummary: 'attendance:read',
  feeCollection: 'fees:read',
  pendingFees: 'fees:read',
  upcomingExams: 'grades:read',
  homeworkPending: 'grades:read',
  assignmentsPending: 'grades:read',
  birthdays: undefined,
  busStatus: undefined,
  libraryActivity: undefined,
  recentAnnouncements: 'communication:read',
  recentNotifications: undefined,
  todayEvents: undefined,
  holidayCalendar: undefined,
  leaveRequests: 'attendance:read',
  pendingApprovals: undefined,
  systemHealth: 'system:logs',
  serverStatus: 'system:logs',
  subscriptionStatus: 'settings:read',
  storageUsage: 'system:logs',
};

export const QUICK_ACTIONS = [
  { id: 'new-student', label: 'New Student', href: '/students/new', permission: 'students:create', shortcut: 'G N' },
  { id: 'new-teacher', label: 'New Teacher', href: '/teachers/new', permission: 'users:create', shortcut: 'G T' },
  { id: 'take-attendance', label: 'Take Attendance', href: '/attendance/take', permission: 'attendance:create', shortcut: 'G A' },
  { id: 'create-homework', label: 'Create Homework', href: '/homework/new', permission: 'grades:create', shortcut: 'G H' },
  { id: 'create-assignment', label: 'Create Assignment', href: '/assignments/new', permission: 'grades:create', shortcut: 'G S' },
  { id: 'generate-report', label: 'Generate Report', href: '/reports/generate', permission: 'reports:create', shortcut: 'G R' },
  { id: 'collect-fee', label: 'Collect Fee', href: '/fees/collect', permission: 'fees:create', shortcut: 'G F' },
  { id: 'send-announcement', label: 'Send Announcement', href: '/communication/announcements/new', permission: 'communication:send', shortcut: 'G M' },
  { id: 'schedule-event', label: 'Schedule Event', href: '/events/new', shortcut: 'G E' },
  { id: 'add-vehicle', label: 'Add Vehicle', href: '/transport/vehicles/new', shortcut: 'G V' },
] as const;

export const ACADEMIC_YEARS = [
  { id: '2024-25', label: '2024-25' },
  { id: '2025-26', label: '2025-26' },
  { id: '2026-27', label: '2026-27' },
] as const;
